/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
// do van hai 20207600
package project.student.management.view;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import project.student.management.controller.QuanLyImpl;
import project.student.management.model.SinhVien;

/**
 *
 * @author seape
 */
public class ChuongTrinh extends javax.swing.JPanel {
    QuanLyImpl ql = new QuanLyImpl();
    DefaultTableModel model;
    /**
     * Creates new form Home
     */
    public ChuongTrinh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        chuongtrinh_tinchiButton = new com.k33ptoo.components.KButton();
        chuongtrinh_mauButton = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        loaisvLabel = new javax.swing.JLabel();

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkGradientFocus(0);
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 255, 255));

        chuongtrinh_tinchiButton.setText("Chương trình tín chỉ");
        chuongtrinh_tinchiButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chuongtrinh_tinchiButtonMouseClicked(evt);
            }
        });
        chuongtrinh_tinchiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuongtrinh_tinchiButtonActionPerformed(evt);
            }
        });

        chuongtrinh_mauButton.setText("Chương trình mẫu");
        chuongtrinh_mauButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chuongtrinh_mauButtonMouseClicked(evt);
            }
        });
        chuongtrinh_mauButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuongtrinh_mauButtonActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ tên", "Mã SV", "Giới tính", "Ngày sinh", "Email", "Khóa học", "Ngành học"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        loaisvLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(chuongtrinh_tinchiButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(chuongtrinh_mauButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(279, 279, 279))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loaisvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chuongtrinh_tinchiButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chuongtrinh_mauButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(loaisvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
     // set TEXT = "" khi click chuot
    private void chuongtrinh_tinchiButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chuongtrinh_tinchiButtonMouseClicked
        // TODO add your handling code here:
        loaisvLabel.setText("Sinh viên tín chỉ");
    }//GEN-LAST:event_chuongtrinh_tinchiButtonMouseClicked

    private void chuongtrinh_mauButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chuongtrinh_mauButtonMouseClicked
        // TODO add your handling code here:
        loaisvLabel.setText("Sinh viên chương trình mẫu");
    }//GEN-LAST:event_chuongtrinh_mauButtonMouseClicked

    private void chuongtrinh_tinchiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuongtrinh_tinchiButtonActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        List<SinhVien> listSV = ql.inDSSV("TC");
        for (SinhVien sinhVien : listSV) {
            String hoTen = sinhVien.getHoTen();
            String maSV = sinhVien.getMaSV();
            String gioiTinh = sinhVien.getGioiTinh();
            String ngaySinh = sinhVien.getNgaySinh();
            String email = sinhVien.getEmail();
            int khoaHoc = sinhVien.getKhoaHoc();
            String nganhHoc = sinhVien.getNganhHoc();
            model.addRow(new Object[]{
            hoTen, maSV, gioiTinh, ngaySinh, email, khoaHoc, nganhHoc
        });
        }
    }//GEN-LAST:event_chuongtrinh_tinchiButtonActionPerformed

    private void chuongtrinh_mauButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuongtrinh_mauButtonActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        List<SinhVien> listSV = ql.inDSSV("CTM");
        for (SinhVien sinhVien : listSV) {
            String hoTen = sinhVien.getHoTen();
            String maSV = sinhVien.getMaSV();
            String gioiTinh = sinhVien.getGioiTinh();
            String ngaySinh = sinhVien.getNgaySinh();
            String email = sinhVien.getEmail();
            int khoaHoc = sinhVien.getKhoaHoc();
            String nganhHoc = sinhVien.getNganhHoc();
            model.addRow(new Object[]{
            hoTen, maSV, gioiTinh, ngaySinh, email, khoaHoc, nganhHoc
        });
        }
    }//GEN-LAST:event_chuongtrinh_mauButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton chuongtrinh_mauButton;
    private com.k33ptoo.components.KButton chuongtrinh_tinchiButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel loaisvLabel;
    // End of variables declaration//GEN-END:variables
}
