
// do van hai 20207600
// pham thai duong 20207595
package project.student.management.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import project.student.management.database.DBConnection;
import project.student.management.model.ChuongTrinhDaoTao;


public class GiaoDienMonHoc extends javax.swing.JPanel {

    private final Connection conn;
    private PreparedStatement ps;
    
    public GiaoDienMonHoc() {
        initComponents();
        conn = DBConnection.getConnection();      
        
        showComboBox();
        


    }
    
    private List<String> layDanhSachTatCaMonHoc() {
        List<String> monHocList = new ArrayList<>();
        try {
            ps = conn.prepareStatement("SELECT tenMonHoc FROM monhoc WHERE 1");
             ResultSet rs = ps.executeQuery();
             
             while (rs.next()) {
                 String danhSachMonHoc = rs.getString(1);
                 System.out.println("" + danhSachMonHoc);
                 monHocList.add(danhSachMonHoc);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(GiaoDienMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (monHocList.isEmpty()) {
            return null;
        } else {
            return monHocList;
        }

    }
    
    private List<String> layDanhSachTatCaMonHoc222() {
        List<String> monHocList = new ArrayList<>();
        try {
            ps = conn.prepareStatement("SELECT tenMonHoc FROM monhoc WHERE 1");
             ResultSet rs = ps.executeQuery();
             
             while (rs.next()) {
                 String danhSachMonHoc = rs.getString(1);
                 System.out.println("" + danhSachMonHoc);
                 monHocList.add(danhSachMonHoc);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(GiaoDienMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (monHocList.isEmpty()) {
            return null;
        } else {
            return monHocList;
        }

    }
    

    
    private List<String> layDanhSachNganhHoc() {
        List<String> monHocList = new ArrayList<>();
        try {
            ps = conn.prepareStatement("SELECT nganhHoc FROM ctdt WHERE 1");
             ResultSet rs = ps.executeQuery();
             
             while (rs.next()) {
                 String danhSachMonHoc = rs.getString(1);
                 System.out.println("" + danhSachMonHoc);
                 monHocList.add(danhSachMonHoc);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(GiaoDienMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (monHocList.isEmpty()) {
            return null;
        } else {
            return monHocList;
        }
    }
    
    private void showComboBox(){ //Thêm dữ liệu vào combobox
        List<String> data = layDanhSachTatCaMonHoc();
        data.add(0, "Mời chọn:"); //data[0]
        for(String s : data){
            monHocCombobox.addItem(s);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        themdiemButton = new com.k33ptoo.components.KButton();
        monHocCombobox = new javax.swing.JComboBox<>();
        kButton1 = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        maSVTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        diemckTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kihocTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        diemgkTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nganhhocCombobox = new javax.swing.JComboBox<>();
        monHocCombobox2 = new javax.swing.JComboBox<>();

        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setkGradientFocus(0);
        kGradientPanel1.setkStartColor(new java.awt.Color(204, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ tên", "Mã SV", "Môn học", "Mã môn", "Số tín chỉ", "Trọng số", "Học kỳ", "Điểm GK", "Điểm CK", "Tổng kết"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(25);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(8).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(9).setPreferredWidth(20);
        }

        themdiemButton.setText("Thêm điểm");
        themdiemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themdiemButtonActionPerformed(evt);
            }
        });

        monHocCombobox.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        monHocCombobox.setMaximumRowCount(7);

        kButton1.setText("Tìm");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã SV");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ngành học");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Kì học");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Điểm GK");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Môn học");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Điểm CK");

        nganhhocCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công nghệ thông tin", "Quản trị kinh doanh", "Kỹ thuật Cơ điện tử" }));
        nganhhocCombobox.setSelectedIndex(-1);
        nganhhocCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nganhhocComboboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1184, Short.MAX_VALUE)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(monHocCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kihocTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(maSVTextField)))
                            .addComponent(jLabel3))
                        .addGap(92, 92, 92)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(41, 41, 41)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(diemgkTextField)
                                    .addComponent(nganhhocCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel4))))
                .addGap(109, 109, 109)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(diemckTextField)
                            .addComponent(monHocCombobox2, 0, 133, Short.MAX_VALUE)))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(themdiemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monHocCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(maSVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nganhhocCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(monHocCombobox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kihocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(diemgkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(diemckTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themdiemButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void themdiemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themdiemButtonActionPerformed
        // TODO add your handling code here:
        ThemDiem themDiem = new ThemDiem();
        themDiem.setVisible(true);
    }//GEN-LAST:event_themdiemButtonActionPerformed

    private void nganhhocComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nganhhocComboboxActionPerformed
        // TODO add your handling code here:
        if(nganhhocCombobox.getSelectedIndex() == 0) {
            monHocCombobox2.removeAllItems();
            monHocCombobox2.addItem("Cấu trúc dữ liệu và giải thuật");
            monHocCombobox2.addItem("Hệ điều hành");
            monHocCombobox2.addItem("Mạng máy tính");
            monHocCombobox2.addItem("Cơ sở dữ liệu");
            monHocCombobox2.addItem("Lập trình hướng đối tượng");
            
        } 
        // quan tri kinh doanh
        if(nganhhocCombobox.getSelectedIndex() == 1) {
            monHocCombobox2.removeAllItems();
            monHocCombobox2.addItem("Quản trị kinh doanh");
            monHocCombobox2.addItem("Quản trị chiến lược");
            monHocCombobox2.addItem("Đạo đức kinh doanh");
            monHocCombobox2.addItem("Quản trị quá trình kinh doanh");
            monHocCombobox2.addItem("Quản trị đa văn hóa");
        }
        //ki thuat co dien tu
        if(nganhhocCombobox.getSelectedIndex() == 2) {
            monHocCombobox2.removeAllItems();
            monHocCombobox2.addItem("Sức bền vật liệu");
           monHocCombobox2.addItem("Cơ sở thiết kế máy");
            monHocCombobox2.addItem("Nguyên lý kỹ thuật điện tử");
            monHocCombobox2.addItem("Linh kiện bán dẫn và vi mạch");
            monHocCombobox2.addItem("Kỹ thuật đo lường và cảm biến");
        }
    }//GEN-LAST:event_nganhhocComboboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField diemckTextField;
    private javax.swing.JTextField diemgkTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField kihocTextField;
    private javax.swing.JTextField maSVTextField;
    private javax.swing.JComboBox<String> monHocCombobox;
    private javax.swing.JComboBox<String> monHocCombobox2;
    private javax.swing.JComboBox<String> nganhhocCombobox;
    private com.k33ptoo.components.KButton themdiemButton;
    // End of variables declaration//GEN-END:variables

    
}
